<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'id' => 1,
                'creator_id' => 1,
                'event_category_id' => 2,
                'name' => 'Cooking for Charity',
                'description' => 'Lets Share Indonesia kembali menggelar kegiatan memasak amal untuk membantu sesama yang membutuhkan, terutama anak-anak panti asuhan.',
                'date' => Carbon::now()->subDays(7)->toDateString(),    // 7 hari yang lalu
                'location' => 'Ramurasa Cooking Studio, Kemang Jakarta Selatan',
                'status' => 'Completed',
                'estimated_participants' => 50,
                'supporting_files' => json_encode(['proposal_charity.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev1.jpg',
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/charity1',
                'organizer_name' => 'Lets Share Indonesia',
                'organizer_phone' => '081234567890',
                'organizer_email' => 'info@letsshare.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'creator_id' => 2,
                'event_category_id' => 3,
                'name' => 'Wonderfood Festival 2025',
                'description' => 'WonderFood Festival adalah sebuah kegiatan sosial yang bertujuan untuk meningkatkan kesadaran masyarakat akan pentingnya pangan bergizi.',
                'image_url' => 'event_images/ev2.jpg',
                'date' => Carbon::now()->subDays(3)->toDateString(),    // 3 hari yang lalu
                'location' => 'Pergudangan Elang Laut, Sentra Industri 1, Blok A5 No.6, Jakarta Utara',
                'status' => 'Completed',
                'estimated_participants' => 200,
                'supporting_files' => json_encode(['pamphlet_wonderfood.jpg']),
                'duration' => 3,
                'start_time' => '09:30:00',
                'end_time' => '12:30:00',
                'group_link' => 'https://chat.whatsapp.com/wonderfood',
                'organizer_name' => 'Wonder Foundation',
                'organizer_phone' => '082112345678',
                'organizer_email' => 'info@wonderfood.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'creator_id' => 3,
                'event_category_id' => 2,
                'name' => 'Plaza Indonesia Culinary Festival',
                'description' => 'Plaza Indonesia Culinary Festival dimulai dengan workshop memasak interaktif yang dipandu oleh chef ternama dari berbagai restoran.',
                'image_url' => 'event_images/ev3.jpg',
                'date' => Carbon::now()->subDays(1)->toDateString(),    // kemarin
                'location' => 'Jalan M.H. Thamrin No.28-30, Gondangdia, Menteng, Jakarta Pusat',
                'status' => 'Canceled',
                'estimated_participants' => 100,
                'supporting_files' => json_encode(['culinary_festival_info.pdf']),
                'duration' => 3,
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'group_link' => 'https://chat.whatsapp.com/culinaryfest',
                'organizer_name' => 'Plaza Indonesia Event Team',
                'organizer_phone' => '081987654321',
                'organizer_email' => 'event@plazaindonesia.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'creator_id' => 4,
                'event_category_id' => 1,
                'name' => 'Tunggadewi Charity',
                'description' => 'TULUNG GAK ADA JARINGAN',
                'estimated_participants' => 80,
                'supporting_files' => json_encode(['laporan_kegiatan.docx']),
                'duration' => 2,
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'group_link' => 'https://chat.whatsapp.com/tunggadewi',
                'organizer_name' => 'Yayasan Tunggadewi',
                'organizer_phone' => '0818000001',
                'organizer_email' => 'tunggadewi@yayasan.org',
                'image_url' => 'event_images/ev4.jpeg',
                'date' => Carbon::now()->toDateString(), // hari ini
                'location' => 'Jl. Ciniru 7 No.23, Kebayoran Baru, Jakarta Selatan',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'creator_id' => 5,
                'event_category_id' => 1,
                'name' => 'Berbagi makanan bersama Yayasan Kanker Payudara',
                'estimated_participants' => 60,
                'supporting_files' => json_encode(['form_donasi.pdf']),
                'duration' => 1,
                'start_time' => '11:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/yayasan_kanker',
                'organizer_name' => 'Yayasan Kanker Payudara',
                'organizer_phone' => '082299998888',
                'organizer_email' => 'support@kankerindonesia.org',
                'description' => 'Dalam kegiatan ini, Yayasan Tunggadewi bersama komunitas peduli kanker akan menyalurkan paket makanan sehat kepada para penderita.',
                'image_url' => 'event_images/ev5.jpeg',
                'date' => Carbon::now()->addDay()->toDateString(),      // besok
                'location' => 'Jl. Wijaya 2, Kebayoran, Jakarta Selatan',
                'status' => 'Coming Soon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'creator_id' => 6,
                'event_category_id' => 1,
                'name' => 'Greeneration Charity',
                'estimated_participants' => 90,
                'supporting_files' => json_encode(['greeneration_guidebook.pdf']),
                'duration' => 2,
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'group_link' => 'https://chat.whatsapp.com/greeneration',
                'organizer_name' => 'Greeneration Foundation',
                'organizer_phone' => '087712345667',
                'organizer_email' => 'info@greeneration.org',
                'description' => 'Greeneration Charity adalah kegiatan sosial yang diinisiasi oleh Greeneration Foundation untuk mengurangi sampah makanan dan membantu sesama.',
                'image_url' => 'event_images/ev6.jpg',
                'date' => Carbon::now()->addDays(2)->toDateString(),    // 2 hari lagi
                'location' => 'Jl. Tikukur No. 6, Gasibu, Sadang Serang, Coblong, Kota Bandung',
                'status' => 'Coming Soon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'creator_id' => 7,
                'event_category_id' => 1,
                'name' => 'Happy Hearts Indonesia Charity',
                'estimated_participants' => 110,
                'supporting_files' => json_encode(['blueprint_sekolah.jpg']),
                'duration' => 3,
                'start_time' => '15:00:00',
                'end_time' => '18:00:00',
                'group_link' => 'https://chat.whatsapp.com/happyhearts',
                'organizer_name' => 'Happy Hearts Indonesia',
                'organizer_phone' => '081122334455',
                'organizer_email' => 'hello@happyhearts.org',
                'description' => 'Happy Hearts Indonesia Charity adalah kegiatan sosial yang bertujuan untuk membangun kembali sekolah-sekolah di daerah terdampak bencana.',
                'image_url' => 'event_images/ev7.jpg',
                'date' => Carbon::now()->addDays(4)->toDateString(),    // 4 hari lagi
                'location' => 'Jl. Anggrek Garuda Blok J No.71 RT.6/RW.3, Kemanggisan, Palmerah, Jakarta Barat',
                'status' => 'Canceled',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'creator_id' => 8,
                'event_category_id' => 3,
                'name' => 'Bumi Sehat Festival 2025',
                'estimated_participants' => 250,
                'supporting_files' => json_encode(['jadwal_festival.pdf']),
                'duration' => 4,
                'start_time' => '10:00:00',
                'end_time' => '14:00:00',
                'group_link' => 'https://chat.whatsapp.com/bumisehat',
                'organizer_name' => 'Yayasan Bumi Sehat',
                'organizer_phone' => '081334567890',
                'organizer_email' => 'info@bumisehat.org',
                'description' => 'Bumi Sehat Festival adalah perayaan kepedulian terhadap kesehatan ibu dan anak, serta lingkungan yang diselenggarakan oleh Yayasan Bumi Sehat.',
                'image_url' => 'event_images/ev8.jpg',
                'date' => Carbon::now()->addDays(6)->toDateString(),    // 6 hari lagi
                'location' => 'Jl. Nyuh Bulan, Banjar Nyuh Kuning, Mas, Ubud, Bali',
                'status' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'creator_id' => 9,
                'event_category_id' => 1,
                'name' => 'Jalinan Rasa',
                'estimated_participants' => 75,
                'supporting_files' => json_encode(['publikasi_jalinanrasa.pdf']),
                'duration' => 2,
                'start_time' => '09:00:00',
                'end_time' => '11:00:00',
                'group_link' => 'https://chat.whatsapp.com/jalinanrasa',
                'organizer_name' => 'Mahasiswa IPB',
                'organizer_phone' => '089812345666',
                'organizer_email' => 'jalinanrasa@ipb.ac.id',
                'description' => 'Jalinan Rasa IPB merupakan kegiatan sosial yang diadakan oleh mahasiswa IPB untuk berbagi makanan kepada masyarakat kurang mampu di sekitar kampus.',
                'image_url' => 'event_images/ev9.jpeg',
                'date' => Carbon::now()->addWeek()->toDateString(),     // 1 minggu lagi
                'location' => 'Kampus IPB Dramaga, Kecamatan Dramaga, Kabupaten Bogor',
                'status' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'creator_id' => 2,
                'event_category_id' => 1,
                'name' => 'Ascott Takes Part Ramadan 2025',
                'description' => 'Ascott Limited berbagi takjil gratis sebagai bentuk kepedulian sosial.',
                'image_url' => 'event_images/ev10.jpg',
                'date' => Carbon::now()->addDays(10)->toDateString(),   // 10 hari lagi
                'location' => 'Oakwood Hotel & Apartments Grand Batam',
                'status' => 'Canceled',
                'estimated_participants' => 300,
                'supporting_files' => json_encode(['takjil_campaign.jpg']),
                'duration' => 1,
                'start_time' => '16:00:00',
                'end_time' => '17:00:00',
                'group_link' => 'https://chat.whatsapp.com/ascottramadan',
                'organizer_name' => 'The Ascott Limited',
                'organizer_phone' => '085566778899',
                'organizer_email' => 'csr@theascott.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'creator_id' => 3,
                'event_category_id' => 1,
                'name' => 'Food Rescue Campaign',
                'description' => 'Kampanye untuk menyelamatkan makanan berlebih dan membagikannya ke panti sosial.',
                'date' => Carbon::now()->addWeeks(2)->toDateString(),   // 2 minggu lagi
                'location' => 'Lapangan Banteng, Jakarta',
                'status' => 'Canceled',
                'estimated_participants' => 120,
                'supporting_files' => json_encode(['rescue_flyer.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev11.jpg',
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/foodrescue',
                'organizer_name' => 'SaveFood Network',
                'organizer_phone' => '081234000111',
                'organizer_email' => 'contact@savefood.org',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'creator_id' => 7,
                'event_category_id' => 3,
                'name' => 'Zero Waste Day',
                'description' => 'Edukasi dan workshop pengurangan sampah makanan di perkotaan.',
                'date' => Carbon::now()->subDays(5)->toDateString(),    // 5 hari yang lalu
                'location' => 'Balai Kota Bandung',
                'status' => 'Completed',
                'estimated_participants' => 150,
                'supporting_files' => json_encode(['poster_zerowaste.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev12.jpg',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'group_link' => 'https://chat.whatsapp.com/zerowasteday',
                'organizer_name' => 'Eco Green Bandung',
                'organizer_phone' => '087899001122',
                'organizer_email' => 'ecogreen@bandung.go.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'creator_id' => 5,
                'event_category_id' => 1,
                'name' => 'Charity Run for Meals',
                'description' => 'Lari bersama sambil berdonasi untuk penyediaan makanan darurat.',
                'date' => Carbon::now()->subDays(2)->toDateString(),    // 2 hari yang lalu
                'location' => 'GBK Senayan Jakarta',
                'status' => 'Canceled',
                'estimated_participants' => 500,
                'supporting_files' => json_encode(['route_map.jpg']),
                'duration' => 3,
                'image_url' => 'event_images/ev13.png',
                'start_time' => '06:00:00',
                'end_time' => '09:00:00',
                'group_link' => 'https://chat.whatsapp.com/charityrun',
                'organizer_name' => 'Jakarta Runners Club',
                'organizer_phone' => '081233344455',
                'organizer_email' => 'info@jrc.org',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'creator_id' => 9,
                'event_category_id' => 1,
                'name' => 'Pasar Gratis Ramah Lingkungan',
                'description' => 'Event berbagi bahan makanan dan edukasi tanpa plastik.',
                'date' => Carbon::now()->toDateString(),                // hari ini
                'location' => 'Alun-alun Bandung',
                'status' => 'Completed',
                'estimated_participants' => 300,
                'supporting_files' => json_encode(['rundown_event.pdf']),
                'duration' => 4,
                'image_url' => 'event_images/ev14.jpg',
                'start_time' => '08:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/pasargratis',
                'organizer_name' => 'Komunitas Hijau',
                'organizer_phone' => '089933221122',
                'organizer_email' => 'komunitashijau@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'creator_id' => 6,
                'event_category_id' => 3,
                'name' => 'Aksi Gizi Nusantara',
                'description' => 'Kampanye nasional untuk edukasi gizi seimbang.',
                'date' => Carbon::now()->addDays(3)->toDateString(),    // 3 hari lagi
                'location' => 'Taman Menteng, Jakarta Pusat',
                'status' => 'Coming Soon',
                'estimated_participants' => 200,
                'supporting_files' => json_encode(['materi_gizi.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev15.jpg',
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/aksigizi',
                'organizer_name' => 'Nusantara Sehat',
                'organizer_phone' => '081566778800',
                'organizer_email' => 'info@nusantarasehat.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'creator_id' => 8,
                'event_category_id' => 2,
                'name' => 'Taste of Unity',
                'description' => 'Festival kuliner lintas budaya untuk solidaritas kemanusiaan.',
                'date' => Carbon::now()->addWeeks(3)->toDateString(),   // 3 minggu lagi
                'location' => 'Taman Mini Indonesia Indah',
                'status' => 'Coming Soon',
                'estimated_participants' => 400,
                'supporting_files' => json_encode(['brosur_event.pdf']),
                'duration' => 4,
                'image_url' => 'event_images/ev16.jpg',
                'start_time' => '13:00:00',
                'end_time' => '17:00:00',
                'group_link' => 'https://chat.whatsapp.com/tasteofunity',
                'organizer_name' => 'Indonesia Culinary Alliance',
                'organizer_phone' => '081245678900',
                'organizer_email' => 'alliance@kuliner.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'creator_id' => 4,
                'event_category_id' => 3,
                'name' => 'Nutrisi untuk Negeri',
                'description' => 'Distribusi makanan sehat untuk keluarga prasejahtera.',
                'date' => Carbon::now()->addDays(15)->toDateString(),   // 15 hari lagi
                'location' => 'Pelataran Monas, Jakarta',
                'status' => 'Pending',
                'estimated_participants' => 250,
                'supporting_files' => json_encode(['infografis_nutrisi.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev17.png',
                'start_time' => '09:00:00',
                'end_time' => '11:00:00',
                'group_link' => 'https://chat.whatsapp.com/nutrisinegeri',
                'organizer_name' => 'Gerakan Nutrisi Baik',
                'organizer_phone' => '085700011223',
                'organizer_email' => 'info@nutrisibaik.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'creator_id' => 1,
                'event_category_id' => 2,
                'name' => 'Kuliner dan Kebaikan',
                'description' => 'Edukasi kuliner sehat dan penggalangan donasi untuk bencana.',
                'date' => Carbon::now()->addMonths(1)->toDateString(),  // 1 bulan lagi
                'location' => 'The Breeze BSD, Tangerang Selatan',
                'status' => 'Pending',
                'estimated_participants' => 150,
                'supporting_files' => json_encode(['kuliner_kebaikan_poster.pdf']),
                'duration' => 3,
                'start_time' => '13:00:00',
                'end_time' => '16:00:00',
                'group_link' => 'https://chat.whatsapp.com/kulinerkebaikan',
                'organizer_name' => 'Komunitas Kuliner Peduli',
                'organizer_phone' => '081222334455',
                'organizer_email' => 'info@kulinerpeduli.id',
                'image_url' => 'event_images/ev18.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 19,
                'creator_id' => 2,
                'event_category_id' => 3,
                'name' => 'Festival Pangan Lokal Nusantara',
                'description' => 'Pameran dan edukasi pangan lokal untuk mendorong ketahanan pangan nasional.',
                'date' => Carbon::now()->subDays(6)->toDateString(),    // 6 hari yang lalu
                'location' => 'Lapangan Parkir Timur Senayan, Jakarta',
                'status' => 'Completed',
                'estimated_participants' => 220,
                'supporting_files' => json_encode(['booklet_festival.pdf']),
                'duration' => 3,
                'image_url' => 'event_images/ev19.jpeg',
                'start_time' => '10:00:00',
                'end_time' => '13:00:00',
                'group_link' => 'https://chat.whatsapp.com/panganlokal',
                'organizer_name' => 'Badan Ketahanan Pangan RI',
                'organizer_phone' => '081223344556',
                'organizer_email' => 'panganlokal@bkp.go.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'creator_id' => 6,
                'event_category_id' => 1,
                'name' => 'Berbagi Pagi Bersama Komunitas',
                'description' => 'Sarapan gratis dan bincang santai tentang gizi bersama komunitas relawan.',
                'date' => Carbon::now()->addDays(30)->toDateString(),   // 30 hari lagi
                'location' => 'Taman Suropati, Menteng, Jakarta Pusat',
                'status' => 'Pending',
                'estimated_participants' => 80,
                'supporting_files' => json_encode(['surat_izin_kegiatan.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev20.jpeg',
                'start_time' => '07:00:00',
                'end_time' => '09:00:00',
                'group_link' => 'https://chat.whatsapp.com/berbagipagi',
                'organizer_name' => 'Komunitas Relawan Muda',
                'organizer_phone' => '081800112233',
                'organizer_email' => 'berbagipagi@relawan.org',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];
        // Hitung kolom 'hour' (integer) dari selisih end_time - start_time
        foreach ($events as &$event) {
            $start = Carbon::parse($event['start_time']);
            $end = Carbon::parse($event['end_time']);
            $event['hour'] = (int) floor($start->diffInMinutes($end) / 60);
        }

        DB::table('events')->insert($events);
    }
}
