<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('events')->insert([
            [
                'id' => 1,
                'creator_id' => 1,
                'event_category_id' => 2,
                'name' => 'Cooking for Charity',
                'description' => 'Lets Share Indonesia kembali menggelar kegiatan memasak amal untuk membantu sesama yang membutuhkan, terutama anak-anak panti asuhan.',
                'date' => '2025-06-20',
                'location' => 'Ramurasa Cooking Studio, Kemang Jakarta Selatan',
                'status' => 'On Going',
                'estimated_participants' => 50,
                'supporting_files' => json_encode(['proposal_charity.pdf']),
                'duration' => 2,
                'image_url' => 'event_images/ev1.jpg',
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/charity1',
                'organizer_name' => 'Lets Share Indonesia',
                'organizer_phone' => '081234567890',
                'organizer_email' => 'info@letsshare.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'creator_id' => 2,
                'event_category_id' => 3,
                'name' => 'Wonderfood Festival 2025',
                'description' => 'WonderFood Festival adalah sebuah kegiatan sosial yang bertujuan untuk meningkatkan kesadaran masyarakat akan pentingnya pangan bergizi.',
                'image_url' => 'event_images/ev2.jpg',
                'date' => '2025-07-09',
                'location' => 'Pergudangan Elang Laut, Sentra Industri 1, Blok A5 No.6, Jakarta Utara',
                'status' => 'Pending',
                'estimated_participants' => 200,
                'supporting_files' => json_encode(['pamphlet_wonderfood.jpg']),
                'duration' => 3,
                'start_time' => '09:30:00',
                'end_time' => '12:30:00',
                'group_link' => 'https://chat.whatsapp.com/wonderfood',
                'organizer_name' => 'Wonder Foundation',
                'organizer_phone' => '082112345678',
                'organizer_email' => 'info@wonderfood.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'creator_id' => 3,
                'event_category_id' => 2,
                'name' => 'Plaza Indonesia Culinary Festival',
                'description' => 'Plaza Indonesia Culinary Festival dimulai dengan workshop memasak interaktif yang dipandu oleh chef ternama dari berbagai restoran.',
                'image_url' => 'event_images/ev3.jpg',
                'date' => '2025-07-03',
                'location' => 'Jalan M.H. Thamrin No.28-30, Gondangdia, Menteng, Jakarta Pusat',
                'status' => 'Coming Soon',
                'estimated_participants' => 100,
                'supporting_files' => json_encode(['culinary_festival_info.pdf']),
                'duration' => 3,
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'group_link' => 'https://chat.whatsapp.com/culinaryfest',
                'organizer_name' => 'Plaza Indonesia Event Team',
                'organizer_phone' => '081987654321',
                'organizer_email' => 'event@plazaindonesia.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'creator_id' => 4,
                'event_category_id' => 1,
                'name' => 'Tunggadewi Charity',
                'description' => 'TULUNG GAK ADA JARINGAN',
                'estimated_participants' => 80,
                'supporting_files' => json_encode(['laporan_kegiatan.docx']),
                'duration' => 2,
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'group_link' => 'https://chat.whatsapp.com/tunggadewi',
                'organizer_name' => 'Yayasan Tunggadewi',
                'organizer_phone' => '0818000001',
                'organizer_email' => 'tunggadewi@yayasan.org',
                'image_url' => 'event_images/ev4.jpeg', 'date' => '2025-08-09', 'location' => 'Jl. Ciniru 7 No.23, Kebayoran Baru, Jakarta Selatan', 
                'status' => 'Canceled',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 5,
                'creator_id' => 5,
                'event_category_id' => 1,
                'name' => 'Berbagi makanan bersama Yayasan Kanker Payudara',
                'estimated_participants' => 60,
                'supporting_files' => json_encode(['form_donasi.pdf']),
                'duration' => 1,
                'start_time' => '11:00:00',
                'end_time' => '12:00:00',
                'group_link' => 'https://chat.whatsapp.com/yayasan_kanker',
                'organizer_name' => 'Yayasan Kanker Payudara',
                'organizer_phone' => '082299998888',
                'organizer_email' => 'support@kankerindonesia.org',
                'description' => 'Dalam kegiatan ini, Yayasan Tunggadewi bersama komunitas peduli kanker akan menyalurkan paket makanan sehat kepada para penderita.',
                'image_url' => 'event_images/ev5.jpeg', 'date' => '2025-08-19', 'location' => 'Jl. Wijaya 2, Kebayoran, Jakarta Selatan', 'status' => 'Completed',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 6,
                'creator_id' => 6,
                'event_category_id' => 1,
                'name' => 'Greeneration Charity',
                'estimated_participants' => 90,
                'supporting_files' => json_encode(['greeneration_guidebook.pdf']),
                'duration' => 2,
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'group_link' => 'https://chat.whatsapp.com/greeneration',
                'organizer_name' => 'Greeneration Foundation',
                'organizer_phone' => '087712345667',
                'organizer_email' => 'info@greeneration.org',
                'description' => 'Greeneration Charity adalah kegiatan sosial yang diinisiasi oleh Greeneration Foundation untuk mengurangi sampah makanan dan membantu sesama.',
                'image_url' => 'event_images/ev6.jpg', 'date' => '2025-09-02', 'location' => 'Jl. Tikukur No. 6, Gasibu, Sadang Serang, Coblong, Kota Bandung', 'status' => 'On Going',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 7,
                'creator_id' => 7,
                'event_category_id' => 1,
                'name' => 'Happy Hearts Indonesia Charity',
                'estimated_participants' => 110,
                'supporting_files' => json_encode(['blueprint_sekolah.jpg']),
                'duration' => 3,
                'start_time' => '15:00:00',
                'end_time' => '18:00:00',
                'group_link' => 'https://chat.whatsapp.com/happyhearts',
                'organizer_name' => 'Happy Hearts Indonesia',
                'organizer_phone' => '081122334455',
                'organizer_email' => 'hello@happyhearts.org',
                'description' => 'Happy Hearts Indonesia Charity adalah kegiatan sosial yang bertujuan untuk membangun kembali sekolah-sekolah di daerah terdampak bencana.',
                'image_url' => 'event_images/ev7.jpg', 'date' => '2025-05-15', 'location' => 'Jl. Anggrek Garuda Blok J No.71 RT.6/RW.3, Kemanggisan, Palmerah, Jakarta Barat', 'status' => 'Coming Soon',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 8,
                'creator_id' => 8,
                'event_category_id' => 3,
                'name' => 'Bumi Sehat Festival 2025',
                'estimated_participants' => 250,
                'supporting_files' => json_encode(['jadwal_festival.pdf']),
                'duration' => 4,
                'start_time' => '10:00:00',
                'end_time' => '14:00:00',
                'group_link' => 'https://chat.whatsapp.com/bumisehat',
                'organizer_name' => 'Yayasan Bumi Sehat',
                'organizer_phone' => '081334567890',
                'organizer_email' => 'info@bumisehat.org',
                'description' => 'Bumi Sehat Festival adalah perayaan kepedulian terhadap kesehatan ibu dan anak, serta lingkungan yang diselenggarakan oleh Yayasan Bumi Sehat.',
                'image_url' => 'event_images/ev8.jpg', 'date' => '2025-06-27', 'location' => 'Jl. Nyuh Bulan, Banjar Nyuh Kuning, Mas, Ubud, Bali', 'status' => 'Pending',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 9,
                'creator_id' => 9,
                'event_category_id' => 1,
                'name' => 'Jalinan Rasa',
                'estimated_participants' => 75,
                'supporting_files' => json_encode(['publikasi_jalinanrasa.pdf']),
                'duration' => 2,
                'start_time' => '09:00:00',
                'end_time' => '11:00:00',
                'group_link' => 'https://chat.whatsapp.com/jalinanrasa',
                'organizer_name' => 'Mahasiswa IPB',
                'organizer_phone' => '089812345666',
                'organizer_email' => 'jalinanrasa@ipb.ac.id',
                'description' => 'Jalinan Rasa IPB merupakan kegiatan sosial yang diadakan oleh mahasiswa IPB untuk berbagi makanan kepada masyarakat kurang mampu di sekitar kampus.',
                'image_url' => 'event_images/ev9.jpeg', 
                'date' => '2025-10-25', 'location' => 'Kampus IPB Dramaga, Kecamatan Dramaga, Kabupaten Bogor', 'status' => 'Pending',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 10,
                'creator_id' => 2,
                'event_category_id' => 1,
                'name' => 'Ascott Takes Part Ramadan 2025',
                'description' => 'Ascott Limited berbagi takjil gratis sebagai bentuk kepedulian sosial.',
                'image_url' => 'event_images/ev10.jpg',
                'date' => '2025-03-13',
                'location' => 'Oakwood Hotel & Apartments Grand Batam',
                'status' => 'Completed',
                'estimated_participants' => 300,
                'supporting_files' => json_encode(['takjil_campaign.jpg']),
                'duration' => 1,
                'start_time' => '16:00:00',
                'end_time' => '17:00:00',
                'group_link' => 'https://chat.whatsapp.com/ascottramadan',
                'organizer_name' => 'The Ascott Limited',
                'organizer_phone' => '085566778899',
                'organizer_email' => 'csr@theascott.com',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
