<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('foods')->insert([
            // Resto: BART (ID: 1)
            ['id' => 1, 'category_id' => 1, 'restaurant_id' => 1, 'name' => 'Grilled Chicken Satay', 'description' => 'Sate ayam panggang dengan bumbu kacang gurih dan aroma khas.', 'stock' => 4, 'image_url' => 'assets/food_images/bart/grilled_chicken_satay.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 2, 'category_id' => 1, 'restaurant_id' => 1, 'name' => 'Spiced Beef Burger', 'description' => 'Burger daging sapi dengan rempah pilihan dan roti lembut.', 'stock' => 3, 'image_url' => 'assets/food_images/bart/spiced_beef_burger.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 3, 'category_id' => 4, 'restaurant_id' => 1, 'name' => 'Truffle Parmesan Fries', 'description' => 'Kentang goreng renyah dengan taburan keju parmesan dan minyak truffle.', 'stock' => 6, 'image_url' => 'assets/food_images/bart/truffle_parmesan_fries.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 4, 'category_id' => 2, 'restaurant_id' => 1, 'name' => 'Chocolate Lava Cake', 'description' => 'Cake cokelat dengan isi cair lembut yang meleleh saat digigit.', 'stock' => 3, 'image_url' => 'assets/food_images/bart/chocolate_lava_cake.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 5, 'category_id' => 3, 'restaurant_id' => 1, 'name' => 'Classic Mojito', 'description' => 'Cocktail segar dengan rasa mint dan jeruk nipis yang menyegarkan.', 'stock' => 5, 'image_url' => 'assets/food_images/bart/classic_mojito.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 6, 'category_id' => 3, 'restaurant_id' => 1, 'name' => 'Cold Brew Coffee', 'description' => 'Kopi seduh dingin dengan aroma kuat dan rasa halus.', 'stock' => 5, 'image_url' => 'assets/food_images/bart/cold_brew_coffee.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 7, 'category_id' => 3, 'restaurant_id' => 1, 'name' => 'Pretty Cinderella', 'description' => 'Mocktail tropis dengan semangka dan jeruk, segar tanpa alkohol.', 'stock' => 5, 'image_url' => 'assets/food_images/bart/pretty_cinderella.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],
            ['id' => 8, 'category_id' => 3, 'restaurant_id' => 1, 'name' => 'Bye-Gone (Non-Alcoholic)', 'description' => 'Koktail non-alkohol dengan jus tropis dan soda yang menyegarkan.', 'stock' => 6, 'image_url' => 'assets/food_images/bart/bye_gone.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],

            // Resto: Sana Sini Restaurant (ID: 2)
            ['id' => 9, 'category_id' => 1, 'restaurant_id' => 2, 'name' => 'Rosmarino Lamb Cut', 'description' => 'Lamb chop panggang premium dengan saus rosemary aromatik.', 'stock' => 3, 'image_url' => 'assets/food_images/sana_sini_restaurant/rosmarino_lamb_cut.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 35000],
            ['id' => 10, 'category_id' => 1, 'restaurant_id' => 2, 'name' => 'Salmon Silk Teriyaki', 'description' => 'Fillet salmon lembut dengan saus teriyaki khas Jepang.', 'stock' => 4, 'image_url' => 'assets/food_images/sana_sini_restaurant/salmon_silk_teriyaki.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 11, 'category_id' => 4, 'restaurant_id' => 2, 'name' => 'Mini Royale Duo', 'description' => 'Slider kecil isi daging sapi dan keju leleh, pas untuk cemilan.', 'stock' => 6, 'image_url' => 'assets/food_images/sana_sini_restaurant/mini_royale_duo.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 12, 'category_id' => 2, 'restaurant_id' => 2, 'name' => 'Berry Blush Layers', 'description' => 'Mille-feuille dengan lapisan raspberry dan krim vanila lembut.', 'stock' => 3, 'image_url' => 'assets/food_images/sana_sini_restaurant/berry_blush_layers.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 13, 'category_id' => 2, 'restaurant_id' => 2, 'name' => 'Mini Choux Citrus Cream', 'description' => 'Kue choux isi krim lemon ringan dan segar.', 'stock' => 4, 'image_url' => 'assets/food_images/sana_sini_restaurant/mini_choux_citrus_cream.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 14, 'category_id' => 3, 'restaurant_id' => 2, 'name' => 'Citrus Noir Brew', 'description' => 'Cold brew teh hitam dengan irisan jeruk sunkist dan es batu.', 'stock' => 5, 'image_url' => 'assets/food_images/sana_sini_restaurant/citrus_noir_brew.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],
            ['id' => 15, 'category_id' => 3, 'restaurant_id' => 2, 'name' => 'Iced Lychee Tea', 'description' => 'Teh dingin segar dengan rasa leci alami.', 'stock' => 7, 'image_url' => 'assets/food_images/sana_sini_restaurant/iced_lychee_tea.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],
            ['id' => 16, 'category_id' => 3, 'restaurant_id' => 2, 'name' => 'Infused Water Mint & Lemon', 'description' => 'Air mineral segar dengan infus mint dan lemon.', 'stock' => 10, 'image_url' => 'assets/food_images/sana_sini_restaurant/infused_water_mint_lemon.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 8000],

            // Resto: KAUM Jakarta (ID: 3)
            ['id' => 17, 'category_id' => 4, 'restaurant_id' => 3, 'name' => 'Tahu Gejrot', 'description' => 'Tahu Sumedang goreng dengan saus gula aren, asam jawa, bawang dan cabai.', 'stock' => 5, 'image_url' => 'assets/food_images/kaum_jakarta/tahu_gejrot.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 18, 'category_id' => 1, 'restaurant_id' => 3, 'name' => 'Sate Sapi Wagyu Maranggi', 'description' => 'Sate daging sapi wagyu dengan bumbu jahe dan lada hitam, leftover dari event.', 'stock' => 3, 'image_url' => 'assets/food_images/kaum_jakarta/sate_sapi_wagyu_maranggi.jpeg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 40000],
            ['id' => 19, 'category_id' => 1, 'restaurant_id' => 3, 'name' => 'Nasi Goreng Ikan Jambal Roti', 'description' => 'Nasi goreng dengan sambal hijau dan ikan jambal roti goreng renyah.', 'stock' => 4, 'image_url' => 'assets/food_images/kaum_jakarta/nasi_goreng_ikan_jambal_roti.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 20, 'category_id' => 1, 'restaurant_id' => 3, 'name' => 'Bistik Jawa', 'description' => 'Steak ribeye sapi marinasi, disajikan dengan kentang dan saus kecap manis.', 'stock' => 2, 'image_url' => 'assets/food_images/kaum_jakarta/bistik_jawa.jpeg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 38000],
            ['id' => 21, 'category_id' => 2, 'restaurant_id' => 3, 'name' => 'Kue Kojo Kukus Saus Kopi', 'description' => 'Kue pandan kukus dengan saus kopi karamel dan kelapa muda parut.', 'stock' => 3, 'image_url' => 'assets/food_images/kaum_jakarta/kue_kojo_kukus-saus_kopi.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 22, 'category_id' => 2, 'restaurant_id' => 3, 'name' => 'Es Bubur Sum-Sum', 'description' => 'Bubur sum-sum dengan bola ubi ungu, gula aren, santan segar, dan es serut.', 'stock' => 4, 'image_url' => 'assets/food_images/kaum_jakarta/es_bubur_sumsum.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: Li Feng (ID: 4)
            ['id' => 23, 'category_id' => 1, 'restaurant_id' => 4, 'name' => 'Honey Glazed BBQ Pork', 'description' => 'Daging babi panggang dengan lapisan saus madu yang manis gurih.', 'stock' => 4, 'image_url' => 'assets/food_images/li_feng/honey_glazed_bbq_pork.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 32000],
            ['id' => 24, 'category_id' => 1, 'restaurant_id' => 4, 'name' => 'Steamed Dim Sum Platter', 'description' => 'Pilihan dim sum kukus seperti siomay, hakau, dan bun lembut.', 'stock' => 5, 'image_url' => 'assets/food_images/li_feng/steamed_dimsum.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 28000],
            ['id' => 25, 'category_id' => 1, 'restaurant_id' => 4, 'name' => 'Salted Egg Prawn', 'description' => 'Udang goreng renyah dilapisi saus telur asin creamy dan gurih.', 'stock' => 3, 'image_url' => 'assets/food_images/li_feng/salted_egg_prawn.jpeg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 26, 'category_id' => 4, 'restaurant_id' => 4, 'name' => 'Spring Rolls', 'description' => 'Lumpia goreng isi sayur segar dan bihun dengan saus cocolan.', 'stock' => 6, 'image_url' => 'assets/food_images/li_feng/spring_rolls.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 27, 'category_id' => 2, 'restaurant_id' => 4, 'name' => 'Mango Pudding', 'description' => 'Puding mangga lembut dengan rasa buah tropis segar.', 'stock' => 4, 'image_url' => 'assets/food_images/li_feng/mango_pudding.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 28, 'category_id' => 2, 'restaurant_id' => 4, 'name' => 'Egg Tart', 'description' => 'Kue tart telur lembut dengan kulit renyah khas Cantonese.', 'stock' => 4, 'image_url' => 'assets/food_images/li_feng/egg_tart.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: Henshin (ID: 5)
            ['id' => 29, 'category_id' => 1, 'restaurant_id' => 5, 'name' => 'Tuna Tiradito', 'description' => 'Irisan tuna segar disajikan dengan saus citrus dan cabai khas Peru.', 'stock' => 4, 'image_url' => 'assets/food_images/henshin/tuna_tiradito.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 35000],
            ['id' => 30, 'category_id' => 1, 'restaurant_id' => 5, 'name' => 'Beef Anticucho Skewers', 'description' => 'Sate daging sapi dengan bumbu khas Peru, disajikan dengan saus chimichurri.', 'stock' => 3, 'image_url' => 'assets/food_images/henshin/beef_anticucho_skewers.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 38000],
            ['id' => 31, 'category_id' => 1, 'restaurant_id' => 5, 'name' => 'Miso Black Cod', 'description' => 'Ikan cod panggang dengan saus miso manis dan tekstur lembut.', 'stock' => 3, 'image_url' => 'assets/food_images/henshin/miso_black_cod.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 45000],
            ['id' => 32, 'category_id' => 4, 'restaurant_id' => 5, 'name' => 'Ceviche Mini Cups', 'description' => 'Mini cup berisi ceviche segar dengan jeruk nipis dan bawang merah.', 'stock' => 5, 'image_url' => 'assets/food_images/henshin/ceviche_mini_cups.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 20000],
            ['id' => 33, 'category_id' => 2, 'restaurant_id' => 5, 'name' => 'Lucuma Cheesecake', 'description' => 'Cheesecake lembut dengan rasa eksotis dari buah lucuma khas Amerika Selatan.', 'stock' => 3, 'image_url' => 'assets/food_images/henshin/lucuma_cheesecake.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 34, 'category_id' => 3, 'restaurant_id' => 5, 'name' => 'Pisco Sour Cocktail', 'description' => 'Cocktail segar dari Pisco, jeruk nipis, dan sedikit foam putih telur.', 'stock' => 5, 'image_url' => 'assets/food_images/henshin/pisco_sour_cocktail.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: Seasonal Tastes (ID: 6)
            ['id' => 35, 'category_id' => 1, 'restaurant_id' => 6, 'name' => 'Grilled Barramundi Fillet', 'description' => 'Fillet ikan barramundi panggang dengan saus lemon butter yang segar.', 'stock' => 4, 'image_url' => 'assets/food_images/seasonal_tastes/grilled_barramundi_fillet.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 35000],
            ['id' => 36, 'category_id' => 1, 'restaurant_id' => 6, 'name' => 'Roast Beef with Mushroom Sauce', 'description' => 'Daging sapi panggang disajikan dengan saus jamur creamy dan kentang panggang.', 'stock' => 3, 'image_url' => 'assets/food_images/seasonal_tastes/roast_beef_with_mushroom_sauce.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 38000],
            ['id' => 37, 'category_id' => 1, 'restaurant_id' => 6, 'name' => 'Nasi Goreng Kampung', 'description' => 'Nasi goreng khas dengan suwiran ayam, irisan cabai, dan kerupuk gurih.', 'stock' => 5, 'image_url' => 'assets/food_images/seasonal_tastes/nasi_goreng_kampung.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 17000],
            ['id' => 38, 'category_id' => 4, 'restaurant_id' => 6, 'name' => 'Spring Rolls', 'description' => 'Lumpia goreng isi sayuran segar dengan saus manis pedas.', 'stock' => 6, 'image_url' => 'assets/food_images/seasonal_tastes/spring_rolls.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 39, 'category_id' => 2, 'restaurant_id' => 6, 'name' => 'Chocolate Mousse', 'description' => 'Mousse cokelat lembut disajikan dengan potongan buah segar.', 'stock' => 4, 'image_url' => 'assets/food_images/seasonal_tastes/chocolate_mousse.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 40, 'category_id' => 3, 'restaurant_id' => 6, 'name' => 'Iced Lemon Tea', 'description' => 'Teh dingin menyegarkan dengan perasan lemon dan es batu.', 'stock' => 5, 'image_url' => 'assets/food_images/seasonal_tastes/iced_lemon_tea.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],

            // Resto: Lyon (ID: 7)
            ['id' => 41, 'category_id' => 1, 'restaurant_id' => 7, 'name' => 'Duck Confit', 'description' => 'Bebek yang dimasak perlahan dalam lemaknya sendiri hingga kulitnya renyah, cita rasa otentik Lyonnais.', 'stock' => 3, 'image_url' => 'assets/food_images/lyon/duck_confit.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 35000],
            ['id' => 42, 'category_id' => 1, 'restaurant_id' => 7, 'name' => 'Beef Bourguignon', 'description' => 'Daging sapi dimasak lama dengan anggur merah Burgundy dan rempah aromatik, tradisi masakan rumah Prancis.', 'stock' => 4, 'image_url' => 'assets/food_images/lyon/beef_bourguignon.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 35000],
            ['id' => 43, 'category_id' => 1, 'restaurant_id' => 7, 'name' => 'Ratatouille', 'description' => 'Hidangan sayur panggang khas Provence dengan perpaduan zucchini, terong, dan paprika, penuh rasa alami.', 'stock' => 5, 'image_url' => 'assets/food_images/lyon/ratatouille.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 22000],
            ['id' => 44, 'category_id' => 4, 'restaurant_id' => 7, 'name' => 'French Baguette with Cheese', 'description' => 'Roti baguette renyah yang dipadukan dengan keju lembut dari region Auvergne, sempurna untuk cemilan klasik.', 'stock' => 6, 'image_url' => 'assets/food_images/lyon/french_baguette_with_cheese.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 45, 'category_id' => 2, 'restaurant_id' => 7, 'name' => 'Crème Brûlée', 'description' => 'Puding krim vanila dengan permukaan gula karamel yang renyah, kenikmatan sederhana khas Prancis.', 'stock' => 4, 'image_url' => 'assets/food_images/lyon/creme_brulee.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 46, 'category_id' => 3, 'restaurant_id' => 7, 'name' => 'French Press Coffee', 'description' => 'Kopi seduh manual dengan aroma penuh dan rasa kaya, pengalaman ngopi ala bistro Lyon.', 'stock' => 5, 'image_url' => 'assets/food_images/lyon/french_press_coffee.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],

            // Resto: OPEN Restaurant (ID: 8)
            ['id' => 47, 'category_id' => 1, 'restaurant_id' => 8, 'name' => 'Beef Stroganoff', 'description' => 'Daging sapi dengan saus krim jamur dan mustard, hidangan klasik Eropa Timur.', 'stock' => 3, 'image_url' => 'assets/food_images/open_restaurant/beef_stroganof.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 20000],
            ['id' => 48, 'category_id' => 1, 'restaurant_id' => 8, 'name' => 'Spaghetti Bolognese', 'description' => 'Spaghetti dengan saus daging sapi, tomat, dan oregano, disajikan dengan keju.', 'stock' => 4, 'image_url' => 'assets/food_images/open_restaurant/spaghetti_bolognese.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 49, 'category_id' => 1, 'restaurant_id' => 8, 'name' => 'Pizza Rendang', 'description' => 'Pizza topping rendang daging sapi dan mozzarella, perpaduan rasa Indonesia-Italia.', 'stock' => 3, 'image_url' => 'assets/food_images/open_restaurant/pizza_rendang.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 50, 'category_id' => 4, 'restaurant_id' => 8, 'name' => 'Saigon Roll', 'description' => 'Lumpia Vietnam isi udang dan sayur dengan saus ikan, leftover dari appetizer.', 'stock' => 5, 'image_url' => 'assets/food_images/open_restaurant/saigon_roll.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 51, 'category_id' => 2, 'restaurant_id' => 8, 'name' => 'Tiramisu', 'description' => 'Kue lapis rasa kopi dan krim mascarpone, ditaburi bubuk kakao, sisa dessert.', 'stock' => 4, 'image_url' => 'assets/food_images/open_restaurant/tiramisu.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 52, 'category_id' => 3, 'restaurant_id' => 8, 'name' => 'Sparkling Lemonade', 'description' => 'Minuman berkarbonasi dengan rasa lemon segar, leftover dari bar.', 'stock' => 5, 'image_url' => 'assets/food_images/open_restaurant/sparkling_lemonade.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],

            // Resto: Tugu Kunstkring Paleis (ID: 9)
            ['id' => 53, 'category_id' => 1, 'restaurant_id' => 9, 'name' => 'Ayam Bakar Tugu', 'description' => 'Ayam bakar dengan bumbu rempah tradisional Jawa, aroma hangat dan rasa autentik khas Nusantara.', 'stock' => 4, 'image_url' => 'assets/food_images/tugu_kunstkring_paleis/ayam_bakar_tugu.jpeg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 20000],
            ['id' => 54, 'category_id' => 1, 'restaurant_id' => 9, 'name' => 'Rendang Daging Sapi', 'description' => 'Daging sapi empuk dimasak dengan santan dan rempah pilihan, warisan kuliner Minang yang kaya rasa.', 'stock' => 3, 'image_url' => 'assets/food_images/tugu_kunstkring_paleis/rendang_daging_sapi.jpeg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 55, 'category_id' => 4, 'restaurant_id' => 9, 'name' => 'Kue Lapis Legit', 'description' => 'Kue lapis dengan tekstur lembut dan rasa manis kompleks, kue tradisional yang mewah.', 'stock' => 5, 'image_url' => 'assets/food_images/tugu_kunstkring_paleis/kue_lapis_legit.jpeg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 56, 'category_id' => 2, 'restaurant_id' => 9, 'name' => 'Es Cendol Jawa', 'description' => 'Minuman segar dengan cendol hijau, santan kental, dan gula merah asli.', 'stock' => 4, 'image_url' => 'assets/food_images/tugu_kunstkring_paleis/es_cendol_jawa.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 57, 'category_id' => 3, 'restaurant_id' => 9, 'name' => 'Jamu Kunyit Asam', 'description' => 'Minuman tradisional berbahan kunyit dan asam jawa, menyegarkan dan menyehatkan.', 'stock' => 5, 'image_url' => 'assets/food_images/tugu_kunstkring_paleis/jamu_kunyit_asem.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],

            // Resto: Sudestada Grill (ID: 10)
            ['id' => 58, 'category_id' => 1, 'restaurant_id' => 10, 'name' => 'Grilled Chimichurri Chicken', 'description' => 'Ayam panggang berbalut saus chimichurri segar khas Amerika Selatan, sisa dari menu utama.', 'stock' => 4, 'image_url' => 'assets/food_images/sudestada_grill/grilled_chimicurri_chicken.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 59, 'category_id' => 1, 'restaurant_id' => 10, 'name' => 'Beef Skewers with Spicy Sauce', 'description' => 'Sate daging sapi dengan saus pedas manis, perpaduan rasa Asia Tenggara dan Amerika Latin.', 'stock' => 3, 'image_url' => 'assets/food_images/sudestada_grill/beef_skewers_with_spicy_sauce.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 60, 'category_id' => 1, 'restaurant_id' => 10, 'name' => 'Seafood Paella', 'description' => 'Nasi paella dengan campuran seafood segar dan rempah, leftover dari buffet spesial.', 'stock' => 3, 'image_url' => 'assets/food_images/sudestada_grill/seafood_paella.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 61, 'category_id' => 4, 'restaurant_id' => 10, 'name' => 'Tostones (Fried Plantains)', 'description' => 'Pisang tanduk goreng renyah khas Karibia, cocok untuk cemilan ringan.', 'stock' => 5, 'image_url' => 'assets/food_images/sudestada_grill/tostones.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 62, 'category_id' => 2, 'restaurant_id' => 10, 'name' => 'Tres Leches Cake', 'description' => 'Kue lembab manis dengan tiga jenis susu, penutup manis ala Amerika Latin.', 'stock' => 4, 'image_url' => 'assets/food_images/sudestada_grill/tres_leches_cake.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 63, 'category_id' => 3, 'restaurant_id' => 10, 'name' => 'Mango Margarita', 'description' => 'Cocktail mangga segar dengan sentuhan tequila, leftover dari bar.', 'stock' => 5, 'image_url' => 'assets/food_images/sudestada_grill/mango_margarita.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: The Japanese (ID: 11)
            ['id' => 64, 'category_id' => 1, 'restaurant_id' => 11, 'name' => 'Salmon Teriyaki', 'description' => 'Fillet salmon panggang dengan saus teriyaki manis dan gurih.', 'stock' => 4, 'image_url' => 'assets/food_images/the_japanese/salmon_teriyaki.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 65, 'category_id' => 1, 'restaurant_id' => 11, 'name' => 'Chicken Katsu Curry', 'description' => 'Ayam goreng tepung renyah disajikan dengan kuah kari Jepang hangat.', 'stock' => 3, 'image_url' => 'assets/food_images/the_japanese/chicken_katsu_curry.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 66, 'category_id' => 1, 'restaurant_id' => 11, 'name' => 'Tempura Udon', 'description' => 'Mie udon dengan tempura udang dan sayuran, cita rasa tradisional.', 'stock' => 3, 'image_url' => 'assets/food_images/the_japanese/tempura_udon.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 20000],
            ['id' => 67, 'category_id' => 4, 'restaurant_id' => 11, 'name' => 'Gyoza', 'description' => 'Pangsit goreng isi daging dan sayur, tekstur renyah dan juicy.', 'stock' => 6, 'image_url' => 'assets/food_images/the_japanese/gyoza.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 68, 'category_id' => 2, 'restaurant_id' => 11, 'name' => 'Matcha Green Tea Cake', 'description' => 'Kue lapis lembut dengan rasa teh hijau matcha yang khas.', 'stock' => 4, 'image_url' => 'assets/food_images/the_japanese/matcha_green_tea_cake.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 69, 'category_id' => 3, 'restaurant_id' => 11, 'name' => 'Yuzu Soda', 'description' => 'Minuman soda dengan rasa jeruk yuzu segar dan menyegarkan.', 'stock' => 5, 'image_url' => 'assets/food_images/the_japanese/yuzu_soda.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],

            // Resto: Giyanti Coffee Roastery (ID: 12)
            ['id' => 70, 'category_id' => 3, 'restaurant_id' => 12, 'name' => 'Single Origin Espresso', 'description' => 'Espresso pekat dengan aroma kopi Nusantara yang kaya dan kompleks.', 'stock' => 6, 'image_url' => 'assets/food_images/giyanti_coffee_roastery/single_origin_espresso.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 71, 'category_id' => 3, 'restaurant_id' => 12, 'name' => 'Cappuccino', 'description' => 'Perpaduan kopi espresso dengan susu berbusa lembut, creamy dan hangat.', 'stock' => 5, 'image_url' => 'assets/food_images/giyanti_coffee_roastery/cappucino.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 14000],
            ['id' => 72, 'category_id' => 3, 'restaurant_id' => 12, 'name' => 'Cold Brew', 'description' => 'Kopi seduh dingin dengan rasa halus dan keasaman rendah, menyegarkan.', 'stock' => 5, 'image_url' => 'assets/food_images/giyanti_coffee_roastery/cold_brew.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 73, 'category_id' => 4, 'restaurant_id' => 12, 'name' => 'Almond Croissant', 'description' => 'Kue croissant renyah dengan isian almond manis dan gurih.', 'stock' => 4, 'image_url' => 'assets/food_images/giyanti_coffee_roastery/almond_croissant.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 74, 'category_id' => 4, 'restaurant_id' => 12, 'name' => 'Banana Bread', 'description' => 'Roti pisang lembut dengan aroma kayu manis yang hangat.', 'stock' => 5, 'image_url' => 'assets/food_images/giyanti_coffee_roastery/banana_bread.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: Arts Cafe (ID: 13)
            ['id' => 75, 'category_id' => 1, 'restaurant_id' => 13, 'name' => 'Slow Roasted Lamb', 'description' => 'Daging kambing panggang lambat dengan rempah pilihan, lembut dan beraroma.', 'stock' => 4, 'image_url' => 'assets/food_images/arts_cafe/slow_roasted_lamb.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 28000],
            ['id' => 76, 'category_id' => 1, 'restaurant_id' => 13, 'name' => 'Grilled Barramundi', 'description' => 'Ikan barramundi panggang dengan saus lemon butter yang segar.', 'stock' => 3, 'image_url' => 'assets/food_images/arts_cafe/grilled_barramundi.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 77, 'category_id' => 4, 'restaurant_id' => 13, 'name' => 'Truffle Fries', 'description' => 'Kentang goreng renyah dengan taburan truffle oil dan parmesan.', 'stock' => 5, 'image_url' => 'assets/food_images/arts_cafe/truffle_fries.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 78, 'category_id' => 2, 'restaurant_id' => 13, 'name' => 'Chocolate Fondant', 'description' => 'Kue cokelat meleleh dengan tekstur lembut dan rasa pekat.', 'stock' => 4, 'image_url' => 'assets/food_images/arts_cafe/chocolate_fondant.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 79, 'category_id' => 3, 'restaurant_id' => 13, 'name' => 'Classic Mojito', 'description' => 'Minuman segar perpaduan mint, jeruk nipis, dan soda.', 'stock' => 5, 'image_url' => 'assets/food_images/arts_cafe/classic_mojito.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],

            // Resto: Plataran Menteng (ID: 14)
            ['id' => 80, 'category_id' => 1, 'restaurant_id' => 14, 'name' => 'Nasi Liwet Solo', 'description' => 'Nasi gurih dimasak dengan santan dan rempah khas, disajikan dengan ayam suwir dan telur.', 'stock' => 4, 'image_url' => 'assets/food_images/plataran_menteng/nasi_liwet_solo.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 20000],
            ['id' => 81, 'category_id' => 1, 'restaurant_id' => 14, 'name' => 'Iga Bakar Bumbu Rujak', 'description' => 'Iga sapi bakar dengan bumbu rujak pedas manis, tekstur empuk dan aroma khas.', 'stock' => 3, 'image_url' => 'assets/food_images/plataran_menteng/iga_bakar-bumbu_rujak.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 28000],
            ['id' => 82, 'category_id' => 4, 'restaurant_id' => 14, 'name' => 'Lemper Ayam', 'description' => 'Ketan isi ayam berbumbu, camilan tradisional yang lezat dan gurih.', 'stock' => 5, 'image_url' => 'assets/food_images/plataran_menteng/lemper_ayam.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 7000],
            ['id' => 83, 'category_id' => 2, 'restaurant_id' => 14, 'name' => 'Es Pisang Ijo', 'description' => 'Pisang dibalut kulit hijau dengan kuah santan manis, segar dan lembut.', 'stock' => 4, 'image_url' => 'assets/food_images/plataran_menteng/es_pisang_ijo.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 84, 'category_id' => 3, 'restaurant_id' => 14, 'name' => 'Wedang Jahe', 'description' => 'Minuman jahe hangat dengan rasa pedas manis yang menenangkan.', 'stock' => 5, 'image_url' => 'assets/food_images/plataran_menteng/wedang_jahe.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],

            // Resto: La Vue Rooftop Bar (ID: 15)
            ['id' => 85, 'category_id' => 1, 'restaurant_id' => 15, 'name' => 'Beef Slider Trio', 'description' => 'Mini burger daging sapi dengan keju cheddar dan saus spesial.', 'stock' => 4, 'image_url' => 'assets/food_images/la_vue_rooftop_bar/beef_slider_trio.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 86, 'category_id' => 4, 'restaurant_id' => 15, 'name' => 'Truffle Popcorn', 'description' => 'Popcorn renyah dengan aroma truffle khas yang menggoda.', 'stock' => 5, 'image_url' => 'assets/food_images/la_vue_rooftop_bar/truffle_popcorn.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 87, 'category_id' => 2, 'restaurant_id' => 15, 'name' => 'Lemon Tart', 'description' => 'Tart lemon dengan rasa asam manis segar dan tekstur lembut.', 'stock' => 4, 'image_url' => 'assets/food_images/la_vue_rooftop_bar/lemon_tart.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],
            ['id' => 88, 'category_id' => 3, 'restaurant_id' => 15, 'name' => 'Signature Negroni', 'description' => 'Cocktail klasik dengan campuran gin, vermouth, dan Campari.', 'stock' => 5, 'image_url' => 'assets/food_images/la_vue_rooftop_bar/signature_negroni.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 89, 'category_id' => 3, 'restaurant_id' => 15, 'name' => 'Virgin Mojito', 'description' => 'Minuman segar perpaduan mint dan jeruk nipis tanpa alkohol.', 'stock' => 6, 'image_url' => 'assets/food_images/la_vue_rooftop_bar/virgin_mojito.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],

            // Resto: Dope Burger & Co. (ID: 16)
            ['id' => 90, 'category_id' => 1, 'restaurant_id' => 16, 'name' => 'Double Dope Beef', 'description' => 'Burger dua lapis daging sapi juicy, keju leleh, dan saus spesial.', 'stock' => 4, 'image_url' => 'assets/food_images/dope_burger_co/double_dope_beef.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 91, 'category_id' => 1, 'restaurant_id' => 16, 'name' => 'Smokey Chicken Burger', 'description' => 'Daging ayam panggang dengan saus BBQ smokey dan selada segar.', 'stock' => 3, 'image_url' => 'assets/food_images/dope_burger_co/smokey_chicken_burger.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 22000],
            ['id' => 92, 'category_id' => 4, 'restaurant_id' => 16, 'name' => 'Mozzarella Bombs', 'description' => 'Bola-bola keju mozzarella goreng renyah, cocok untuk cemilan.', 'stock' => 5, 'image_url' => 'assets/food_images/dope_burger_co/mozzarella_bombs.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 93, 'category_id' => 4, 'restaurant_id' => 16, 'name' => 'Seasoned Curly Fries', 'description' => 'Kentang goreng keriting dengan bumbu spesial khas Dope Burger.', 'stock' => 6, 'image_url' => 'assets/food_images/dope_burger_co/seasoned_curly_fries.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 94, 'category_id' => 2, 'restaurant_id' => 16, 'name' => 'Banana Fritter Bites', 'description' => 'Potongan pisang goreng crispy dengan taburan gula kayu manis.', 'stock' => 4, 'image_url' => 'assets/food_images/dope_burger_co/banana_fritter_bites.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],
            ['id' => 95, 'category_id' => 3, 'restaurant_id' => 16, 'name' => 'Cola Twist', 'description' => 'Minuman soda klasik dengan sentuhan lemon segar.', 'stock' => 5, 'image_url' => 'assets/food_images/dope_burger_co/cola_twist.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 8000],
            ['id' => 96, 'category_id' => 3, 'restaurant_id' => 16, 'name' => 'Vanilla Milkshake', 'description' => 'Milkshake vanila kental dengan whipped cream di atasnya.', 'stock' => 4, 'image_url' => 'assets/food_images/dope_burger_co/vanilla_milkshake.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 12000],

            // Resto: Paradigma (ID: 17)
            ['id' => 97, 'category_id' => 1, 'restaurant_id' => 17, 'name' => 'Grilled Wagyu Beef', 'description' => 'Daging wagyu panggang dengan saus red wine, tekstur lembut dan kaya rasa.', 'stock' => 3, 'image_url' => 'assets/food_images/paradigma/grilled_wagyu_beef.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 30000],
            ['id' => 98, 'category_id' => 1, 'restaurant_id' => 17, 'name' => 'Seared Tuna Tataki', 'description' => 'Tuna segar dengan lapisan luar yang dibakar, disajikan dengan saus ponzu.', 'stock' => 4, 'image_url' => 'assets/food_images/paradigma/seared_tuna_tataki.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 28000],
            ['id' => 99, 'category_id' => 4, 'restaurant_id' => 17, 'name' => 'Truffle Fries', 'description' => 'Kentang goreng renyah dengan taburan minyak truffle dan parmesan.', 'stock' => 5, 'image_url' => 'assets/food_images/paradigma/truffle_fries.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 14000],
            ['id' => 100, 'category_id' => 2, 'restaurant_id' => 17, 'name' => 'Salted Caramel Panna Cotta', 'description' => 'Panna cotta lembut dengan saus karamel asin yang gurih dan manis.', 'stock' => 4, 'image_url' => 'assets/food_images/paradigma/salted_caramel_panacotta.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 18000],
            ['id' => 101, 'category_id' => 3, 'restaurant_id' => 17, 'name' => 'Espresso Martini', 'description' => 'Cocktail kopi dengan sentuhan vodka dan manis yang seimbang.', 'stock' => 5, 'image_url' => 'assets/food_images/paradigma/espresso_martini.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: Bandar Djakarta (ID: 18)
            ['id' => 102, 'category_id' => 1, 'restaurant_id' => 18, 'name' => 'Ikan Bakar Jimbaran', 'description' => 'Ikan segar dibakar dengan bumbu khas Jimbaran yang gurih dan pedas.', 'stock' => 4, 'image_url' => 'assets/food_images/bandar_djakarta/ikan_bakar_jimbaran.png', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 28000],
            ['id' => 103, 'category_id' => 1, 'restaurant_id' => 18, 'name' => 'Udang Goreng Mentega', 'description' => 'Udang segar dimasak dengan mentega dan bawang putih harum.', 'stock' => 4, 'image_url' => 'assets/food_images/bandar_djakarta/udang_goreng_mentega.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 25000],
            ['id' => 104, 'category_id' => 1, 'restaurant_id' => 18, 'name' => 'Kepiting Saus Padang', 'description' => 'Kepiting segar dimasak dengan saus Padang pedas dan nikmat.', 'stock' => 3, 'image_url' => 'assets/food_images/bandar_djakarta/kepiting_saus_padang.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 32000],
            ['id' => 105, 'category_id' => 4, 'restaurant_id' => 18, 'name' => 'Tahu Isi', 'description' => 'Tahu goreng renyah dengan isian sayur dan daging cincang.', 'stock' => 5, 'image_url' => 'assets/food_images/bandar_djakarta/tahu_isi.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            // ['id' => 106, 'category_id' => 3, 'restaurant_id' => 18, 'name' => 'Es Teh Manis', 'description' => 'Teh manis dingin segar yang cocok untuk menemani hidangan.', 'stock' => 6, 'image_url' => null, 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 10000],

            // Resto: Cinnamon (ID: 19)
            ['id' => 107, 'category_id' => 1, 'restaurant_id' => 19, 'name' => 'Butter Chicken', 'description' => 'Ayam dimasak dengan saus mentega berbumbu rempah khas India yang kaya dan lembut.', 'stock' => 4, 'image_url' => 'assets/food_images/cinnamon/butter_chicken.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 22000],
            ['id' => 108, 'category_id' => 1, 'restaurant_id' => 19, 'name' => 'Lamb Rogan Josh', 'description' => 'Daging kambing dimasak dengan rempah-rosemary dan saus tomat pekat.', 'stock' => 3, 'image_url' => 'assets/food_images/cinnamon/lamb_rogan_josh.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 26000],
            ['id' => 109, 'category_id' => 4, 'restaurant_id' => 19, 'name' => 'Samosa', 'description' => 'Pastel goreng isi kentang dan kacang polong dengan rempah pilihan.', 'stock' => 5, 'image_url' => 'assets/food_images/cinnamon/samosa.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 110, 'category_id' => 2, 'restaurant_id' => 19, 'name' => 'Gulab Jamun', 'description' => 'Bola susu manis yang direndam dalam sirup gula mawar hangat.', 'stock' => 4, 'image_url' => 'assets/food_images/cinnamon/gulab_jamun.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 14000],
            ['id' => 111, 'category_id' => 3, 'restaurant_id' => 19, 'name' => 'Mango Lassi', 'description' => 'Minuman yoghurt mangga segar dan manis, khas India.', 'stock' => 5, 'image_url' => 'assets/food_images/cinnamon/mango_lassi.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],

            // Resto: Bunga Rampai (ID: 20)
            ['id' => 112, 'category_id' => 1, 'restaurant_id' => 20, 'name' => 'Ayam Betutu', 'description' => 'Ayam kampung dengan bumbu khas Bali, dimasak dengan rempah lengkap dan santan.', 'stock' => 4, 'image_url' => 'assets/food_images/bunga_rampai/ayam_betutu.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 17000],
            ['id' => 113, 'category_id' => 1, 'restaurant_id' => 20, 'name' => 'Ikan Bakar Jimbaran', 'description' => 'Ikan segar dibakar dengan bumbu Bali tradisional yang pedas dan gurih.', 'stock' => 3, 'image_url' => 'assets/food_images/bunga_rampai/ikan_bakar_jimbaran.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 22000],
            ['id' => 114, 'category_id' => 4, 'restaurant_id' => 20, 'name' => 'Lemper Ayam', 'description' => 'Ketan isi ayam berbumbu yang lezat, camilan khas Nusantara.', 'stock' => 5, 'image_url' => 'assets/food_images/bunga_rampai/lemper_ayam.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 8000],
            ['id' => 115, 'category_id' => 2, 'restaurant_id' => 20, 'name' => 'Kue Lapis Legit', 'description' => 'Kue tradisional lapis dengan rasa manis dan tekstur lembut.', 'stock' => 4, 'image_url' => 'assets/food_images/bunga_rampai/kue_lapis_legit.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 15000],
            ['id' => 116, 'category_id' => 3, 'restaurant_id' => 20, 'name' => 'Es Cendol', 'description' => 'Minuman tradisional segar dari cendol, santan, dan gula merah.', 'stock' => 5, 'image_url' => 'assets/food_images/bunga_rampai/es_cendol.jpg', 'exp_datetime' => Carbon::now()->addDays(rand(7, 90)), 'price' => 8000],
        ]);
    }
}
